version: '3.8'

services:
  # WordPress Service
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: 'mehops'
      WORDPRESS_DB_PASSWORD: 'mehops'
      WORDPRESS_DB_NAME: 'mehops'
    volumes:
      - wp_wp:/var/www/html/
    networks:
      - wp_net

  # Nginx Reverse Proxy Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - wp_net

  # Database Service
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mehops'
      MYSQL_DATABASE: 'mehops'
      MYSQL_USER: 'mehops'
      MYSQL_PASSWORD: 'mehops'
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - wp_net

# Volumes for persistent data storage
volumes:
  wp_db:
    name: wp_db
  wp_wp:
    name: wp_wp

# Custom network for internal communication between services
networks:
  wp_net:
    name: wp_net
    driver: bridge
