version: '3.7'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: localhost
    container_name: gitlab
    ports:
      - "80:80"
      - "443:443"
      - "2424:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
