# cluster.yml
# RKE cluster configuration for Mehops project

nodes:
  # Controller Node: Manages the cluster state and control plane components
  - address: "192.168.56.10"
    user: mehops
    role:
      - "controlplane"
      - "etcd"
    hostname_override: "controller"
    
  # Worker Node 1: Runs container workloads
  - address: "192.168.56.11"
    user: mehops
    role:
      - "worker"
    hostname_override: "worker1"

  # Worker Node 2: Runs container workloads
  - address: "192.168.56.12"
    user: mehops
    role:
      - "worker"
    hostname_override: "worker2"

  # Worker Node 3: Runs container workloads
  - address: "192.168.56.13"
    user: mehops
    role:
      - "worker"
    hostname_override: "worker3"

# If set to true, RKE will not fail when unsupported Docker version is found.
ignore_docker_version: true

# The Kubernetes version used.
# You can find available versions here: https://github.com/rancher/rke/releases
kubernetes_version: "v1.28.8-rancher2-2" # Using a recent stable version

# Set the name of the Kubernetes cluster
cluster_name: "mehops-cluster"

# --- Services Configuration ---
services:
  etcd:
    snapshot: true
    backup_config:
      interval_hours: 4
      retention: 10

  kube-api:
    # Enable audit logging for the API server
    audit_log:
      enabled: true
      configuration:
        max_age: 6
        max_backup: 6
        max_size: 110
        path: /var/log/kube-audit/audit-log.json
        format: json
        policy:
          apiVersion: audit.k8s.io/v1
          kind: Policy
          omitStages:
            - "RequestReceived"
          rules:
            - level: RequestResponse
              resources:
              - group: ""
                resources: ["pods"]
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: 30000-32767
    always_pull_images: true

  kube-controller:
    cluster_cidr: 10.42.0.0/16

  kubelet:
    cluster_domain: cluster.local
    extra_args:
      max-pods: 250
    fail_swap_on: false # Recommended for lab environments that might have swap enabled

# --- Network Plugin ---
network:
  plugin: calico

# --- Authentication & Authorization ---
authentication:
  strategy: x509
  sans:
    # Add all your node IPs and hostnames here
    - "192.168.56.10"
    - "192.168.56.11"
    - "192.168.56.12"
    - "192.168.56.13"
    - "controller"
    # You might want to add a load balancer or DNS entry for the API server
    # - "kube-api.mehops.local"

authorization:
  mode: rbac

# --- Monitoring Provider ---
monitoring:
  provider: metrics-server