# ======================= Filebeat inputs ===========================
# Defines where Filebeat should look for log files.
filebeat.inputs:
- type: log
  enabled: true
  paths:
    # Path to the Nginx logs that we mounted from the Docker container to the worker1 VM.
    # Ensure this path exists and is populated by your Nginx container.
    - /opt/wordpress/nginx/logs/*.log

  fields: # Add custom fields to easily identify these logs in Kibana
    service: nginx
    host: worker1
    log_type: mehops_nginx_access
  fields_under_root: true # Places the above fields at the top level of the log document


# ======================= Outputs ===================================
# We are sending logs to Logstash, so we disable the default Elasticsearch output.
# output.elasticsearch:
#   hosts: ["localhost:9200"]

# ---------------------------- Logstash Output ------------------------------
output.logstash:
  # The IP of worker2 (where Logstash is) and the Beats input port we configured.
  hosts: ["192.168.56.12:5044"]
